inherit_from: .rubocop_todo.yml
require: rubocop-rspec

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/BeginEndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: begin

# Minimize git diff when adding/re-ordering items
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/NumericLiterals:
  Enabled: false

# Match Ruby style guide which is not Rubocop's default
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    'default': '()'
    '%i': '[]'
    '%I': '[]'
    '%w': '[]'
    '%W': '[]'
    '%r': '{}'

Style/MultilineBlockChain:
  Enabled: false

# It would be nice but it tends to lead to banal descriptions
Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  IgnoredMethods: [lambda, proc, it, expect]

Style/ClassAndModuleChildren:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true
  EnforcedStyle: integral

Style/SlicingWithRange:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true
  EnforcedStyle: separated

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/AsciiComments:
  Enabled: true
  AllowedChars:
    - ∑

Style/HashAsLastArrayItem:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: true

Style/GlobalStdStream:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/StringConcatenation:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/ClassEqualityComparison:
  Enabled: true

Style/CombinableLoops:
  Enabled: true

Style/KeywordParametersOrder:
  Enabled: true

Style/RedundantSelfAssignment:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: false

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: true

FactoryBot/CreateList:
  Enabled: true
  EnforcedStyle: n_times

Capybara/FeatureMethods:
  Enabled: false

# Too many offenses
RSpec/AnyInstance:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/DescribedClass:
  Enabled: true
  EnforcedStyle: explicit

RSpec/DescribedClassModuleWrapping:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectChange:
  Enabled: true
  EnforcedStyle: block

RSpec/ExpectInHook:
  Enabled: false

RSpec/FilePath:
  Enabled: true
  CustomTransform:
    RuboCop: rubocop
    RSpec: rspec
    PDFs: pdfs

# While it's a good guiding principle, it's often not practical, e.g. request
# and feature tests
RSpec/MultipleExpectations:
  Enabled: false

RSpec/StubbedMock:
  Enabled: true

RSpec/ReturnFromStub:
  Enabled: true
  EnforcedStyle: and_return

Lint/DuplicateRequire:
  Enabled: true

Lint/EmptyFile:
  Enabled: true

Lint/HashCompareByIdentity:
  Enabled: true

Lint/IdentityComparison:
  Enabled: true

Lint/RedundantSafeNavigation:
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true

Lint/UselessMethodDefinition:
  Enabled: true

Lint/UselessTimes:
  Enabled: true

AllCops:
  Exclude:
    - 'vendor/**/*'